### ISSUE TITLE
CommunityImage / LogoImage

### ISSUE THREAD

**Issue by nno3onn** [ODUGI/Odugi#6]

**Comment by krokerdile** [comment]
코드를 한번 쭉 둘러 봤는데 나눠져 있는게 맞는 방향인 것 같아요? 
communityImage랑 LogoImage가 아니라 communityImage 랑 CommunityLogo가 다른 요소로 작성 되어 있어서 헷갈렸던 것 같음.
alarm을 옮겨서 communityLogo에서 알람이 추가 되면 알람 부분을 띄워 줄 수있도록 작업 해줘야 할듯

**Comment by krokerdile** [comment]
라고 생각을 하고 코드를 짜려고 했는데 communityLogo가 atom이고 communityImage는 거기에 alarm이 들어간 molecule 으로 작성을 해둔 거 같아서 좀 더 깔끔하게 정리를 하고 이름을 바꾸는 방향으로 생각을 해봐야 되지 않을까...
